
# build singularity

FROM golang:1.11.2-stretch as singularity_builder 

RUN apt-get update \
    && apt-get -y install libssl-dev uuid-dev \
    && mkdir -p $GOPATH/src/github.com/sylabs
WORKDIR $GOPATH/src/github.com/sylabs
RUN git clone -b v3.0.1 https://github.com/sylabs/singularity.git 
WORKDIR $GOPATH/src/github.com/sylabs/singularity
RUN ./mconfig -s -S -p /opt/singularity
WORKDIR $GOPATH/src/github.com/sylabs/singularity/builddir
RUN make \
    && make install


# build final container

FROM python:3.6.7-stretch

COPY --from=singularity_builder /opt/singularity /opt/singularity

WORKDIR /src
COPY . /src/geneflow
    
RUN apt-get update \
    && apt-get -y install git \
    && apt-get -y install squashfs-tools \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -U pip \
    && git clone -b v0.7.3 https://github.com/TACC/agavepy \
    && pip install ./agavepy \
    && pip install ./geneflow \
    && rm -rf /src/* \
    && rm -rf /root/.cache/pip/*

ENV PATH /opt/singularity/bin:$PATH
